
import { ONBOARDING_CONSTANTS } from '@/constants/onboarding.constants';

export const getCategoryColor = (category: string): string => {
  switch (category) {
    case ONBOARDING_CONSTANTS.CATEGORIES.SETUP: 
      return ONBOARDING_CONSTANTS.COLORS.SETUP;
    case ONBOARDING_CONSTANTS.CATEGORIES.FIRST_ACTION: 
      return ONBOARDING_CONSTANTS.COLORS.FIRST_ACTION;
    case ONBOARDING_CONSTANTS.CATEGORIES.EXPLORATION: 
      return ONBOARDING_CONSTANTS.COLORS.EXPLORATION;
    case ONBOARDING_CONSTANTS.CATEGORIES.ACHIEVEMENT: 
      return ONBOARDING_CONSTANTS.COLORS.ACHIEVEMENT;
    default: 
      return ONBOARDING_CONSTANTS.COLORS.DEFAULT;
  }
};
