// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msnrffdhmxdmpzosajau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zbnJmZmRobXhkbXB6b3NhamF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNDgyMjYsImV4cCI6MjA2MTcyNDIyNn0.uwi_Y2R4MQwCpasEO94GFBhKqszRtZUNfDAXQhvdUv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);